### ISSUE TITLE
API docs error: 'decs' instead of  'desc' 

### ISSUE THREAD

**Issue by nikolay-borzov** [avg206/movie-api-server#1]
`api.json` says:

```
{
  "in": "query",
  "name": "sortOrder",
  "schema": {
    "type": "string"
   },
   "description": "Value to define sort direction - 'decs' or 'asc'"
},
```

but should be "Value to define sort direction - 'desc' or 'asc'".

Probably it's better to add enumeration here like for `searchBy` field

**Comment by avg206** [comment]
Thanks for your note, it's fixed!
